pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Building..'
                bat 'dir'
                bat 'mvn -version'
                dir('hello-world') {
                    bat 'dir'
                    bat 'mvn clean package'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                bat 'dir'
                dir('hello-world') {
                    bat 'dir'
                    bat 'mvn test'
                }
            }
        }
        stage('Build Image') {
            steps {
                echo 'Building Image..'
                bat 'docker --version'
                dir('hello-world') {
                    bat 'dir'
                    bat 'docker build --tag=spring-hello-world:0.0.2-JENKINS -f src/main/docker/Dockerfile .'
                    bat 'docker image ls'
                }
            }
        }
        stage('Deploy') {
            steps {
                timeout(time: 15, unit: "MINUTES") {
                    input message: 'Do you want to approve the deployment?', ok: 'Yes'
                }
                echo 'Deploying....'
                dir('hello-world') {
                    bat 'docker run -p 8001:8001 --memory=256m --memory-reservation=128m --name spring-hello-world -d spring-hello-world:0.0.2-JENKINS'
                }
            }
        }
    }
}