spring.application.name: hello-world
server.port: ${SERVER_PORT:8001}

spring:
  cloud:
    config:
      enabled: false

management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

springdoc.swagger-ui.path: /swagger-ui-custom.html
eureka.client.serviceUrl.defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://127.0.0.1:8761/eureka}

app.internal:
  service:
    user-service: user-service
  path:
    get-users: /v1/user-service/users
